### ISSUE TITLE
Column names in df for CalcTheory

### ISSUE THREAD

**Issue by alanhuebner10** [alanhuebner10/Gboot#2]
Run 
data("Brennan.3.1")
test <- CalcGTheoryCI(Data = Brennan.3.1, B = 1000, type = "pi")
head(test)

The first seven column names are correct, but last three columns should not be  var_i, var_p,  var_p. They should be the Dstudy quantities AbsErrVar, GenCoef  DepCoef.

**Comment by saberry** [comment]
Fixed
