### ISSUE TITLE
Error thrown for sim_dat_2nested()

### ISSUE THREAD

**Issue by alanhuebner10** [alanhuebner10/Gboot#4]
Run
test_sim <- sim_dat_2nested(
            np = 40, 
            ni = 6, 
            nr = 3, 
            sig_ = 1, 
            sig_r = 2, 
            sig_pr = 2, 
            sig_i.r = 3, 
            sig_pi.r = 4
)

Throws error "Error in construct_DesMat2_nested(np, ni, nr) : could not find function "construct_DesMat2_nested"
However, running
lsf.str("package:Gboot")
returns
construct_DesMat_2nested : function (np, ni, nr)  
So, there is a mismatch, i.e. DesMat_2 vs. DesMat2

**Comment by saberry** [comment]
Fixed
